version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: twitter_clone_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter_clone_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=twitter_clone_db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=root
    ports:
      - "80:80"  # Dit opent poort 80 voor de PHP ingebouwde server
    command: php -S 0.0.0.0:80 -t public  # Start de PHP ingebouwde server op poort 80
    depends_on:
      - db

volumes:
  db_data:
