version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: twitter_clone_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: twitter_clone_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    container_name: twitter_clone_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    command: php artisan serve --host=0.0.0.0 --port=9000
    ports:
      - "9000:9000"

  redis:
    image: redis:alpine
    container_name: twitter_clone_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data:
