name: CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write          

    steps:
      - uses: actions/checkout@v4

      - name: Github Tag Bump
        id: tag_bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.0.2
          DEFAULT_BUMP: patch

    outputs:
      new_version: ${{ steps.tag_bump.outputs.new_tag }}

  build-and-deploy-service:
    runs-on: ubuntu-latest
    needs: generate-version

    env:
      APP_NAME: twitterclone
      SERVICE_NAME: socialmedia
      HELM_CHART_VERSION: 0.1.4

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ env.APP_NAME }}:${{ needs.generate-version.outputs.new_version }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.APP_NAME }}:${{ needs.generate-version.outputs.new_version }}

      - name: Setup Helm
        uses: Azure/setup-helm@v1

      - name: Deploy Helm chart
        run: |
          helm upgrade \
          ${{ env.SERVICE_NAME }}-service \
          ./helm/microservice \
          --version ${{ env.HELM_CHART_VERSION }} \
          -f helm/values.yaml \
          -n ${{ env.SERVICE_NAME }} \
          --set image.tag=${{ needs.generate-version.outputs.new_version }} \
          --install \
          --create-namespace \
          --wait
